---
title: "Analysis - active learning and faculty qualifications"
author: "Saurabh Khanna"
date: "`r Sys.Date()`"
output: 
  github_document:
    toc: true
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE, fig.retina = 4)
```

```{r message=FALSE, warning=FALSE}
# Libraries
library(tidyverse)
library(haven)
library(stargazer)
library(AER)
library(sandwich)
library(lmtest)

# Parameters
stufac_file <- here::here("data", "all_appended.dta")
stu_file <- here::here("data", "stu_admin_all_latest.dta")
```


```{r}
df_stu <- 
  read_dta(stu_file) %>% 
  mutate(
    reservation = dplyr::recode(reservation, "Non-reservation" = 0L, "Reservation" = 1L, .default = NA_integer_)
  )

df_stufac <- 
  read_dta(stufac_file) %>% 
  left_join(
    df_stu %>% 
      select(stdid, classid, reservation, ea_stud_group_criteria),
    by = "stdid"
  ) %>%
  filter(ea_stud_group_criteria == 2)
```

Identify sections

```{r}
sections <-
  df_stufac %>% 
  count(classid, course_name) %>% 
  arrange(classid, desc(n), course_name) %>%
  group_by(classid) %>% 
  top_n(1, wt = n) %>%
  distinct(classid, .keep_all = T) %>% 
  left_join(
    df_stufac %>% 
      count(classid, course_name, facid),
    by = c("classid", "course_name")
  ) %>% 
  filter(n.y >= 3) %>%
  group_by(classid, course_name) %>% 
  mutate(n_sections = n()) %>% 
  filter(n_sections > 1) %>% 
  transmute(
    classid, 
    course_name, 
    facid,
    section = str_c(classid, row_number())
  ) %>%
  ungroup() %>% 
  left_join(
    df_stufac %>% 
      select(stdid, classid, course_name, facid), by = c("classid", "course_name", "facid")
  ) %>% 
  select(stdid, section) %>% 
  distinct(stdid, .keep_all = T) %>% 
  arrange(stdid, section)
```



```{r}
sections %>% 
  left_join(df_stu, by = "stdid") %>% 
  write_dta(here::here("data", "stu_admin_data_with_sections.dta"), version = 13)
```


### Done till here


Randomization checks

```{r, eval = F}
seg_scores %>%
  filter(grade == 2) %>% 
  lm(stu_diversity ~ female + age + score + father_ed_ind + mother_ed_ind + school_years_english + classid, data = .) %>% 
  summary()

seg_scores %>% 
  filter(grade == 2) %>% 
  lm(fac_diversity ~ female + age + score + father_ed_ind + mother_ed_ind + school_years_english + classid, data = .) %>% 
  summary()
```


Table 1 (All)

```{r}
lm1 <-
  seg_scores %>%
  filter(grade == 2) %>% 
  filter(res_stdid == 1) %>% 
  lm(seg_score ~ stu_diversity + classid + female + age + score + father_ed_ind + mother_ed_ind + school_years_english, data = .)

lm2 <-
  seg_scores %>%
  filter(grade == 2) %>% 
  filter(res_stdid == 0) %>% 
  lm(seg_score ~ stu_diversity + classid + female + age + score + father_ed_ind + mother_ed_ind + school_years_english, data = .)

lm3 <-
  seg_scores %>%
  filter(grade == 2) %>% 
  filter(res_stdid == 1) %>% 
  lm(seg_score ~ fac_diversity + classid + female + age + score + father_ed_ind + mother_ed_ind + school_years_english, data = .)

lm4 <-
  seg_scores %>%
  filter(grade == 2) %>% 
  filter(res_stdid == 0) %>% 
  lm(seg_score ~ fac_diversity + classid + female + age + score + father_ed_ind + mother_ed_ind + school_years_english, data = .)

rob_se <-
  list(
    sqrt(diag(vcovHC(lm1, type = "HC1"))),
    sqrt(diag(vcovHC(lm2, type = "HC1"))),
    sqrt(diag(vcovHC(lm3, type = "HC1"))),
    sqrt(diag(vcovHC(lm4, type = "HC1")))
  )

stargazer(
  lm1, lm2, lm3, lm4,
  se = rob_se,
  title = "Table 4: Effects of diversity of classmates and faculty on segregation",
  header = F,
  digits = 2,
  model.numbers = F,
  dep.var.caption  = "Segregation (by student reservation status)",
  dep.var.labels.include  = F,
  column.labels   = c("Reservation", "Non-reservation", "Reservation", "Non-reservation"),
  covariate.labels = c("Diversity of classmates", "Diversity of faculty", "Constant"),
  keep = c("stu_diversity", "fac_diversity", "Constant"),
  keep.stat = c("n"),
  type = "html",
  out = "testing.html",
  notes = c(
    "All models control for pre-treatment student characteristics and department-year fixed effects."
  )
)
```


Table 2 (Elite/Selective)

```{r}
lm1 <-
  seg_scores %>%
  filter(grade == 2) %>% 
  filter(res_stdid == 1, elite == 1) %>% 
  lm(seg_score ~ stu_diversity + classid + female + age + score + father_ed_ind + mother_ed_ind + school_years_english, data = .)

lm2 <-
  seg_scores %>%
  filter(grade == 2) %>% 
  filter(res_stdid == 0, elite == 1) %>% 
  lm(seg_score ~ stu_diversity + classid + female + age + score + father_ed_ind + mother_ed_ind + school_years_english, data = .)

lm3 <-
  seg_scores %>%
  filter(grade == 2) %>% 
  filter(res_stdid == 1, elite == 1) %>% 
  lm(seg_score ~ fac_diversity + classid + female + age + score + father_ed_ind + mother_ed_ind + school_years_english, data = .)

lm4 <-
  seg_scores %>%
  filter(grade == 2) %>% 
  filter(res_stdid == 0, elite == 1) %>% 
  lm(seg_score ~ fac_diversity + classid + female + age + score + father_ed_ind + mother_ed_ind + school_years_english, data = .)

rob_se <-
  list(
    sqrt(diag(vcovHC(lm1, type = "HC1"))),
    sqrt(diag(vcovHC(lm2, type = "HC1"))),
    sqrt(diag(vcovHC(lm3, type = "HC1"))),
    sqrt(diag(vcovHC(lm4, type = "HC1")))
  )

stargazer(
  lm1, lm2, lm3, lm4,
  se = rob_se,
  title = "Table 5: Effects of diversity of classmates and faculty on segregation at selective colleges",
  header = F,
  digits = 2,
  model.numbers = F,
  dep.var.caption  = "Segregation (by student reservation status)",
  dep.var.labels.include  = F,
  column.labels   = c("Reservation", "Non-reservation", "Reservation", "Non-reservation"),
  covariate.labels = c("Diversity of classmates", "Diversity of faculty", "Constant"),
  keep = c("diversity", "fac_res", "Constant"),
  keep.stat = c("n"),
  type = "html",
  out = "testing.html",
  notes = c(
    "All models control for pre-treatment student characteristics and department-year fixed effects."
  )
)
```


Table 3 (Non-elite/non-selective)

```{r}
lm1 <-
  seg_scores %>%
  filter(grade == 2) %>% 
  filter(res_stdid == 1, elite == 0) %>% 
  lm(seg_score ~ stu_diversity + classid + female + age + score + father_ed_ind + mother_ed_ind + school_years_english, data = .)

lm2 <-
  seg_scores %>%
  filter(grade == 2) %>% 
  filter(res_stdid == 0, elite == 0) %>% 
  lm(seg_score ~ stu_diversity + classid + female + age + score + father_ed_ind + mother_ed_ind + school_years_english, data = .)

lm3 <-
  seg_scores %>%
  filter(grade == 2) %>% 
  filter(res_stdid == 1, elite == 0) %>% 
  lm(seg_score ~ fac_diversity + classid + female + age + score + father_ed_ind + mother_ed_ind + school_years_english, data = .)

lm4 <-
  seg_scores %>%
  filter(grade == 2) %>% 
  filter(res_stdid == 0, elite == 0) %>% 
  lm(seg_score ~ fac_diversity + classid + female + age + score + father_ed_ind + mother_ed_ind + school_years_english, data = .)

rob_se <-
  list(
    sqrt(diag(vcovHC(lm1, type = "HC1"))),
    sqrt(diag(vcovHC(lm2, type = "HC1"))),
    sqrt(diag(vcovHC(lm3, type = "HC1"))),
    sqrt(diag(vcovHC(lm4, type = "HC1")))
  )

stargazer(
  lm1, lm2, lm3, lm4,
  se = rob_se,
  title = "Table 6: Effects of diversity of classmates and faculty on segregation at non-selective colleges",
  header = F,
  digits = 2,
  model.numbers = F,
  dep.var.caption  = "Segregation (by student reservation status)",
  dep.var.labels.include  = F,
  column.labels   = c("Reservation", "Non-reservation", "Reservation", "Non-reservation"),
  covariate.labels = c("Diversity of classmates", "Diversity of faculty", "Constant"),
  keep = c("diversity", "fac_res", "Constant"),
  keep.stat = c("n"),
  type = "html",
  out = "testing.html",
  notes = c(
    "All models control for pre-treatment student characteristics and department-year fixed effects."
  )
)
```

